# ------------------------------------------------------------------------------
# ACCUEIL

PwebMain_accueil:
    path:      /
    defaults:  { _controller: PwebMainBundle:Main:index }

PwebMain_triprixcroissant:
    path:      /triprixcroissant
    defaults:  { _controller: PwebMainBundle:Main:indextriprixcroissant }

PwebMain_triprixdecroissant:
    path:      /triprixdecroissant
    defaults:  { _controller: PwebMainBundle:Main:indextriprixdecroissant }

PwebMain_trirecent:
    path:      /trirecent
    defaults:  { _controller: PwebMainBundle:Main:indextrirecent }

# ------------------------------------------------------------------------------
# VOIR UN PRODUIT

PwebMain_voir:
    path:      /article/{id}
    defaults:  { _controller: PwebMainBundle:Main:voir }

# ------------------------------------------------------------------------------
# COMMANDES ADMINISTRATEUR : AJOUTER, MODIFIER, SUPPRIMMER, GERER, VALIDER
        
PwebMain_ajouter:
    path:      /ajouter
    defaults:  { _controller: PwebMainBundle:Main:ajouter }
 
PwebMain_modifier:
    path:      /modifier/{id}
    defaults:  { _controller: PwebMainBundle:Main:modifier }
    requirements:
        id:  \d+
 
PwebMain_supprimer:
    path:      /supprimer/{id}
    defaults:  { _controller: PwebMainBundle:Main:supprimer }
    requirements:
        id:  \d+

PwebMain_ajoutercategories:
    path:      /categories/ajouter/{id}
    defaults:  { _controller: PwebMainBundle:Main:ajoutercategories }
        
PwebMain_supprimercategories:
    path:      /categories/supprimer/{id}
    defaults:  { _controller: PwebMainBundle:Main:supprimercategories }

PwebMain_categoriesgerer:
    path:      /categories/gerer
    defaults:  { _controller: PwebMainBundle:Main:categoriesgerer }

PwebMain_statut:
    path:      /commandes/statut
    defaults:  { _controller: PwebMainBundle:Main:statut }

# ------------------------------------------------------------------------------
# ESPACE CLIENT, PANIER, VALIDATION

PwebMain_espaceclient:
    path:      /espaceclient
    defaults:  { _controller: PwebMainBundle:Main:espaceclient }

PwebMain_connecter:
    path:      /connecter
    defaults:  { _controller: PwebMainBundle:Main:connecter }

PwebMain_deconnecter:
    path:      /deconnecter
    defaults:  { _controller: PwebMainBundle:Main:deconnecter }

PwebMain_enregistrer:
    path:      /enregistrer
    defaults:  { _controller: PwebMainBundle:Main:enregistrer }

PwebMain_profileuser:
    path:      /profileuser
    defaults:  { _controller: PwebMainBundle:Main:profileuser }

PwebMain_panier:
    path:      /panier
    defaults:  { _controller: PwebMainBundle:Main:panier }

PwebMain_ajouterpanier:
    path:      /panier/ajouter/{idproduit}
    defaults:  { _controller: PwebMainBundle:Main:ajouterproduitaupanier }

# ------------------------------------------------------------------------------
# INITIALISER

PwebMain_initialiseclear:
    path:      /initialiser/clear
    defaults:  { _controller: PwebMainBundle:Main:initialiseclear }

PwebMain_initialisetruncatetable:
    path:      /initialiser/truncatetable
    defaults:  { _controller: PwebMainBundle:Main:initialisetruncatetable }
    
PwebMain_initialiseproduits:
    path:      /initialiser/produits
    defaults:  { _controller: PwebMainBundle:Main:initialiseproduits }

PwebMain_initialisecategories:
    path:      /initialiser/categories
    defaults:  { _controller: PwebMainBundle:Main:initialisecategories }