parameters:
#    Pweb_Main.example.class: Pweb\MainBundle\Example

services:
#    Pweb_Main.example:
#        class: %Pweb_Main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
